# == In this configuration you setup AlchemyÂ´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: text
  hint: false
  unique: false
  contents:
  - name: body
    type: EssenceRichtext
- name: intro
  hint: false
  unique: true
  contents:
  - name: image
    type: EssencePicture
  - name: image_credit
    type: EssenceCredit
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
  - name: body
    type: EssenceRichtext
- name: image
  hint: false
  unique: false
  contents:
  - name: image
    type: EssencePicture
  - name: caption
    type: EssenceText
  - name: link
    type: EssenceLink
  - name: image_credit
    type: EssenceCredit
- name: quote
  hint: false
  unique: false
  contents:
  - name: quote
    type: EssenceRichtext
  - name: quotee
    type: EssenceText
- name: rich_image
  hint: false
  unique: false
  contents:
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: image_alignment
    type: EssenceSelect
    default: Left
    settings:
      select_values: [Left, Right]
  - name: caption
    type: EssenceText
  - name: quote
    type: EssenceRichtext
  - name: quotee
    type: EssenceText
  - name: body
    type: EssenceRichtext
- name: section
  hint: false
  unique: false
  contents:
  - name: title
    type: EssenceText
- name: foyer_card
  hint: false
  unique: false
  contents:
  - name: url
    type: EssenceLink
  - name: state_1_label
    type: EssenceText
  - name: state_1_title
    type: EssenceText
  - name: state_1_image
    type: EssencePicture
  - name: state_2_title
    type: EssenceText
  - name: state_2_body
    type: EssenceRichtext
  - name: state_2_image
    type: EssencePicture
  - name: state_3_logo
    type: EssencePicture
  - name: state_3_image
    type: EssencePicture
