# == In this configuration you setup AlchemyÂ´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: text
  hint: false
  unique: false
  contents:
  - name: body
    type: EssenceRichtext
- name: intro
  hint: false
  unique: true
  contents:
  - name: background_image
    type: EssencePicture
  - name: background_image_caption
    type: EssenceText
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
- name: image
  hint: false
  unique: false
  contents:
  - name: image
    type: EssencePicture
  - name: caption
    type: EssenceText
  - name: link
    type: EssenceLink
- name: quote
  hint: false
  unique: false
  contents:
  - name: quote
    type: EssenceRichtext
  - name: quotee
    type: EssenceText
- name: rich_image
  hint: false
  unique: false
  contents:
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: caption
    type: EssenceText
  - name: quote
    type: EssenceRichtext
  - name: quotee
    type: EssenceText
  - name: body
    type: EssenceRichtext
