# == In this configuration you setup AlchemyÂ´s element layouts.
#
# For further informations please see http://guides.alchemy-cms.com/create_elements.html

- name: text
  hint: false
  unique: false
  contents:
  - name: body
    type: EssenceRichtext
- name: intro
  hint: false
  unique: false
  contents:
  - name: image
    type: EssencePicture
  - name: image_credit
    type: EssenceCredit
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
  - name: body
    type: EssenceRichtext
  - name: label
    type: EssenceText
  - name: partner_logo
    type: EssencePicture
  - name: hide_in_credits
    type: EssenceBoolean
- name: featured_exhibition
  hint: false
  unique: true
  contents:
  - name: image
    type: EssencePicture
  - name: image_credit
    type: EssenceCredit
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
  - name: body
    type: EssenceRichtext
  - name: label
    type: EssenceText
  - name: partner_logo
    type: EssencePicture

- name: image
  hint: false
  unique: false
  contents:
  - name: image
    type: EssencePicture
  - name: image_credit
    type: EssenceCredit
  - name: hide_in_credits
    type: EssenceBoolean
- name: quote
  hint: false
  unique: false
  contents:
  - name: quote
    type: EssenceRichtext
  - name: quotee
    type: EssenceText
- name: rich_image
  hint: false
  unique: false
  contents:
  - name: title
    type: EssenceText
  - name: sub_title
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: image_alignment
    type: EssenceSelect
    default: Left
    settings:
      select_values: [Left, Right]
  - name: image_credit
    type: EssenceCredit
  - name: quote
    type: EssenceRichtext
  - name: quotee
    type: EssenceText
  - name: body
    type: EssenceRichtext
  - name: hide_in_credits
    type: EssenceBoolean
- name: section
  hint: false
  unique: false
  contents:
  - name: title
    type: EssenceText
- name: foyer_card
  hint: false
  unique: false
  contents:
  - name: url
    type: EssenceLink
  - name: state_1_label
    type: EssenceText
  - name: state_1_title
    type: EssenceText
  - name: state_1_image
    type: EssencePicture
  - name: state_2_title
    type: EssenceText
  - name: state_2_body
    type: EssenceRichtext
  - name: state_2_image
    type: EssencePicture
  - name: state_3_logo
    type: EssencePicture
  - name: state_3_image
    type: EssencePicture
- name: embed
  contents:
  - name: embed
    type: EssenceHtml
- name: navigation
  contents:
  - name: previous
    type: EssenceLink
  - name: next
    type: EssenceLink
- name: chapter
  contents:
  - name: label
    type: EssenceText
  - name: image
    type: EssencePicture
  - name: link
    type: EssenceLink
- name: credit_intro
  contents:
  - name: title
    type: EssenceText
  - name: body
    type: EssenceRichtext
  - name: image
    type: EssencePicture
- name: image_compare
  contents:
  - name: image_1
    type: EssencePicture
  - name: image_2
    type: EssencePicture
- name: promo
  contents:
  - name: image
    type: EssencePicture
  - name: text1
    type: EssenceText
  - name: text2
    type: EssenceText
  - name: button_text
    type: EssenceText
  - name: link
    type: EssenceLink

