# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: page
  unique: true
  elements: [text]


- name: exhibition_intro
  unique: false
  elements: [text, image, rich_image]
