<%
if ENV.key?('VCAP_SERVICES')
  services = JSON.parse(ENV['VCAP_SERVICES'])
  postgres_config = services['compose-for-postgresql']
end
fail 'No Postgres service found in environment.' if postgres_config.nil?
service_config = postgres_config.first
postgres_url = service_config['credentials']['uri']
%>
production:
  url: "<%= postgres_url %>"
